<?php
/**
 * @user: thanatos <thanatos915@163.com>
 */

namespace api\common\controllers;

use Yii;
use common\components\vendor\RestController;
use common\models\forms\RegisterForm;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;

class UserController extends RestController
{

    /**
     * @param $action
     * @return bool
     * @throws BadRequestHttpException
     * @throws ForbiddenHttpException
     * @author thanatos <thanatos915@163.com>
     */
    public function beforeAction($action)
    {
        if ($action->id == 'bind') {
            if (Yii::$app->user->isGuest) {
//                throw new ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 用户账号密码登录
     * @author thanatos <thanatos915@163.com>
     */
    public function actionLogin()
    {

    }

    /**
     * 绑定手机号
     * @return RegisterForm
     * @throws BadRequestHttpException
     * @author thanatos <thanatos915@163.com>
     */
    public function actionBind()
    {
        $model = new RegisterForm(['scenario' => RegisterForm::SCENARIO_BIND]);
        if ($model->load(Yii::$app->request->post(), '') && ($result = $model->bind())) {
            return $model;
        } else {
            throw new BadRequestHttpException($model->getStringErrors());
        }
    }





}