<?php
/**
 * Created by PhpStorm.
 * User: thanatos
 * Date: 2018/4/23
 * Time: 下午1:41
 */

namespace api\controllers;


use api\common\models\wechat\EventMessageHandle;
use common\components\traits\FuncTrait;
use common\extension\Code;
use common\models\forms\LoginForm;
use common\models\MemberAccessToken;
use common\models\MemberOauth;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\rest\Controller;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;

class WechatController extends Controller
{
    public $enableCsrfValidation = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->off(Response::EVENT_BEFORE_SEND, [Yii::$app->response, 'formatMessage']);
    }

    /**
     * @throws \EasyWeChat\Kernel\Exceptions\BadRequestException
     * @throws \EasyWeChat\Kernel\Exceptions\InvalidArgumentException
     * @throws \EasyWeChat\Kernel\Exceptions\InvalidConfigException
     */
    public function actionServer()
    {
        $app = Yii::$app->wechat->app;

        $app->server->push(EventMessageHandle::class);

        $response = $app->server->serve();

        $response->send();
    }



}
